### ISSUE TITLE
Add harmonized resource label for easier mass deletion

### ISSUE THREAD

**Issue by ppxl** [cloudogu/k8s-dogu-operator#70]
A CES instance contains currently a lot of different resources labels, sometimes even none at all.

Please change the app label to app: ces for easier mass deletion of CES relevant resources. The decision fell to this label key/value because the k8s-dogu-operator already deploys this label to a wide range of resources.

See also cloudogu/k8s-ces-setup#34

**Comment by nhinze23** [comment]
Resolved via #71
