### ISSUE TITLE
Stabilize image pull mechanism 

### ISSUE THREAD

**Issue by nhinze23** [cloudogu/k8s-dogu-operator#89]
In install and upgrade procedures the dogu operator fetches container images to extract custom kubernetes ressources.
With a slow connection or even a disconnect the pull throws an error and the whole installation/upgrade fails.

The operator should handle this like kubernetes the ImagePullBackOff. Retry on errors with an increasing backoff time.

**Comment by ppxl** [comment]
For the future reader: With virtualbox this can be tested by shutting down the VM network like so:
```bash
# pull the cable
for vm in `vboxmanage list runningvms | awk '{ print $2}'`; do vboxmanage controlvm "${vm}" setlinkstate1 off; done
# insert virtual RJ45 cable ;)
for vm in `vboxmanage list runningvms | awk '{ print $2}'`; do vboxmanage controlvm "${vm}" setlinkstate1 on; done
```
